name: Daily
on:
  push:
    branches:
      - master
  schedule:
    # - cron: "0 0 * * *"
    - cron: "0 16 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install @coder-calendar/svg tslib extract-colors@1.1.22 canvas node-fetch@2.6.6 mime-types
      - uses: bubkoo/use-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/github-script@v6
        id: calendar
        with:
          github-token: ${{ env.BOT_TOKEN }}
          result-encoding: string
          script: |
            const { generateSVG } = require('@coder-calendar/svg')
            const script = require('./scripts/coder-calendar.js')
            const svg = generateSVG('bubkoo')
            return await script({github, context, core, svg})
      - uses: wow-actions/daily-saying@v1
        id: saying
      # - uses: wow-actions/download-upload@v1
      #   id: upload
      #   with:
      #     GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
      #     url: ${{ steps.saying.outputs.best_picture }}
      #     dir: assets/daily-saying
      #     commit_message: "chore: upload daily-saying image [skip ci]"
      - uses: actions/github-script@v6
        id: sayingSvg
        with:
          github-token: ${{ env.BOT_TOKEN }}
          result-encoding: string
          script: |
            const script = require('./scripts/daily-saying.js')
            const metadata = {
              date: `${{ steps.saying.outputs.date }}`,
              image: `${{ steps.saying.outputs.best_picture }}`,
              content: `${{ steps.saying.outputs.content }}`,
              translation: `${{ steps.saying.outputs.translation }}`,
            }
            return await script({github, context, core, metadata})
      - uses: wow-actions/update-file@v1
        with:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
          path: README.md
          content: |
            <p align="center">
              <img src="${{ steps.sayingSvg.outputs.result }}" height="196"/>
              <img src="https://365dots.vercel.app?d=${{ steps.saying.outputs.date }}" height="196"/>
            </p>
          commit_message: "chore: daily saying [skip ci]"
          opening_comment: "<!-- [START DAILY SAYING] -->"
          closing_comment: "<!-- [END DAILY SAYING] -->"
