name: Coder Calendar
description: Apply semantic-release's automatic publishing to a monorepo
author: bubkoo <bubkoo.wy@gmail.com>

inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication
    required: true
  dir:
    description: Directory path to save the coder-calender svg
    required: true
  commit_message:
    description: Commit message when update the file
    required: false
    default: 'chore: generate daily coder-calender [skip ci]'

outputs:
  svg:
    description: The generated svg string
  file:
    description: The saved svg file path

runs:
  using: node12
  main: dist/index.js

branding:
  icon: send
  color: green
