name: Daily
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 16 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node version to 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install
        run: npm install @coder-calendar/svg
      - uses: bubkoo/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: actions/github-script@v6
        id: calendar
        with:
          github-token: ${{ env.bot_token }}
          result-encoding: string
          script: |
            const { generateSVG } = require('@coder-calendar/svg')
            const script = require('./scripts/coder-calendar.js')
            return await script({github, context, core, generateSVG})
      - uses: wow-actions/daily-saying@v1
        id: saying
      - uses: wow-actions/download-upload@v1
        id: upload
        with:
          GITHUB_TOKEN: ${{ env.bot_token }}
          url: ${{ steps.saying.outputs.best_picture }}
          dir: assets/daily-saying
      - uses: wow-actions/update-file@v1
        with:
          GITHUB_TOKEN: ${{ env.bot_token }}
          path: README.md
          content: |
            <h3 align="center">${{ steps.saying.outputs.date }}</h3>
            <p align="center">${{ steps.saying.outputs.content }}</p>
            <p align="center">${{ steps.saying.outputs.translation }}</p>
            <p align="center"><img src="${{ steps.upload.outputs.filepath }}"/></p>
          commit_message: "chore: daily saying [skip ci]"
          opening_comment: "<!-- [START DAILY SAYING] -->"
          closing_comment: "<!-- [END DAILY SAYING] -->"
